### PR TITLE
First week merge into master.

### PR DESCRIPTION
**Pull request by ARIKBOGA**
At least 2 reviewer we need. One week work is going to be moved into master after merging.

### CODE REVIEW

**Review by ARIKBOGA — COMMENTED** [review]
@ARIKBOGA

**Review by zeroist — APPROVED** [review]
test passed  perfectly

**Review by ecnracr — APPROVED** [review]
good job team!!!

**Review by ARIKBOGA — COMMENTED** [review]
Good work folks

**Pull request merged**
